# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13-LOgjenEB411fLtB3VBLAjSULyoLhQr
"""

# The == operator checks if two values are equal. But there is no === operator in Python but in JavaScript 


# Program of Range with Start, Step and Stop

for x in range(10):
     print(f"number {x}")
    

    #range(start, stop, step):
  
for i in range(4,50,3):
             print(i,end=" ")

# use of break Statement 
for i in range(10) : 
    if(i == 5) : 
        break
    i += 1                        # It will break the loop when 'i' will be equal to 5.
    print(i)

# use of if-else
x=10
y=20
if x<y:
    print("Hii")
else:
    print("Byee")

# use of Pass Statement
x=10
y=4
if x<y:
    pass
else:
    print("Hello")